location ~ /\.(?!well-known/) {
    deny all;
    access_log off;
    log_not_found off;
}

location ~* /(?:uploads|files)/.*\.php$ {
    deny all;
}

location ~* /(wp-config\.php|readme\.html|license\.txt)$ {
    deny all;
}

location ~* \.(?:sql|log|ini|conf|bak|old|orig|save|swp|dist)$ {
    deny all;
}

location ~* /(?:composer\.(?:json|lock)|package(?:-lock)?\.json|yarn\.lock)$ {
    deny all;
}
